name: Run Tests on Push/Merge to Main

on:
  push:
    branches:
      - main
    paths:
      - 'challenge3/challenge3-backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'challenge3/challenge3-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give execute permissions to gradlew
        run: chmod +x challenge3/challenge3-backend/gradlew

      - name: Build and test with Gradle
        run: cd challenge3/challenge3-backend && ./gradlew build test --no-daemon


